orders/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('payment/<int:pk>', views.PaymentDetailView.as_view(), name="payment"),
    path('placeorder/', views.PlaceOrderView.as_view(), name="placeorder"),
    path('list/', views.OrderListView.as_view(), name="list"),
    path('detail/<int:pk>', views.OrderDetailView.as_view(), name="detail"),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name="list"),
    path('<slug>', views.ProductDetailView.as_view(), name="detail"),
    path('addtocart/', views.AddToCartView.as_view(), name="addtocart"),
    path('removefromcart/', views.RemoveFromCartView.as_view(), name="removefromcart"),
    path('cart/', views.CartView.as_view(), name="cart"),
    path('checkout/', views.CheckoutView.as_view(), name="checkout"),
    path('search/', views.SearchListView.as_view(), name="search"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.CreateProfileView.as_view(), name="create"),
    path('update/', views.UpdateProfileView.as_view(), name="update"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('orders.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
'''Models for Orders and Order Items in an e-commerce application.'''
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    ''' Order model '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    total_qty = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Approved'),
            ('C', 'Created'),
            ('R', 'Rejected'),
            ('P', 'Pending'),
            ('S', 'Shipped'),
            ('D', 'Delivered'),
        )
    )
    
    def __str__(self):
        return f"Order N. {self.pk}"

class OrderItem(models.Model):
    ''' Order Item model '''
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    price_promo = models.FloatField(default=0)
    quantity = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)
    
    def __str__(self):
        return f"Item from {self.order}"
    class Meta:
        ''' Meta class for OrderItem '''
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'

orders/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from django.contrib import messages

from products.models import Variation
from .models import Order, OrderItem

from utils import utils

class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('profile:create')
        
        return super().dispatch(*args, **kwargs)
    
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        return qs
class PaymentDetailView(DispatchLoginRequiredMixin, DetailView):
    template_name = 'order/payment.html'
    model = Order
    pk_url_kwarg = 'pk'
    context_object_name = 'order'
    
    def post(self, request, *args, **kwargs):
        order = self.get_object()
        messages.success(
            request,
            'Payment successful! Thank you for shopping with us.'
        )
        return redirect('product:list')

    

class PlaceOrderView(View):
    template_name = 'order/payment.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'You need to log in.'
            )
            return redirect('profile:create')
        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Empty cart.'
            )
            return redirect('product:list')

        cart = self.request.session.get('cart')
        cart_variation_ids = [v for v in cart]
        bd_variations = list(
            Variation.objects.select_related('product')
            .filter(id__in=cart_variation_ids)
        )
        for variation in bd_variations:
            vid = str(variation.id)

            stock = variation.stock
            qtd_cart = cart[vid]['quantity']
            unit_price = cart[vid]['unit_price']
            promo_unit_price = cart[vid]['promotional_unit_price']

            error_msg_stock = ''

            if stock < qtd_cart:
                cart[vid]['quantity'] = stock
                cart[vid]['quantitative_pricing'] = stock * unit_price
                cart[vid]['promotional_quantitative_pricing'] = stock * \
                    promo_unit_price

                error_msg_stock = 'Insufficient stock for some products in your cart. '\
                    'We have reduced the quantity of these products. Please '\
                    'check which products were affected below.'

                if error_msg_stock:
                    messages.error(
                        self.request,
                        error_msg_stock
                    )

                    self.request.session.save()
                    return redirect('product:cart')

        cart_total_qty = utils.cart_total_qty(cart)
        cart_total_amount = utils.cart_totals(cart)

        order = Order(
            user=self.request.user,
            total=cart_total_amount,
            total_qty=cart_total_qty,
            status='C',
        )

        order.save()

        OrderItem.objects.bulk_create(
            [
                OrderItem(
                    order=order,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_pricing'],
                    price_promo=v['promotional_quantitative_pricing'],
                    quantity=v['quantity'],
                    image=v['image'],
                ) for v in cart.values()
            ]
        )

        del self.request.session['cart']

        return redirect(
            reverse(
                'order:payment',
                kwargs={
                    'pk': order.pk,
                }
            )
        )

class OrderDetailView(DispatchLoginRequiredMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'order/detail.html'
    pk_url_kwarg = 'pk'

class OrderListView(DispatchLoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'order/list.html'
    paginate_by = 10
    ordering = ['-id']
    

templates/partials/_cart.html
{% load static %}
{% load bsfilters %}


<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for row in cart.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{ row.image }}">
            </td>
            <td>
                <a href="{% url 'product:detail' row.slug %}">
                    {{ row.product_name }}
                </a>
                <a class="ml-3" href="{% url 'product:removefromcart' %}?vid={{ row.variation_id }}">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{ row.variation_name }}</td>

            <td>
                {{ row.quantity }} x
                {% if row.promotional_unit_price %}
                {{ row.promotional_unit_price }}
                {% else %}
                {{ row.unit_price }}
                {% endif %}
            </td>

            {% if row.promotional_quantitative_pricing %}
            <td>{{ row.promotional_quantitative_pricing|format_price_usa }}</td>
            {% else %}
            <td>{{ row.quantitative_pricing|format_price_usa }}</td>
            {% endif %}

        </tr>
        {% endfor %}


    </table>
</div>

templates/partials/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col d-flex justify-content-center align-items-center py-2">
                Made with Django by Bruno Silva
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

templates/partials/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="{% static 'libs/fontawesome/css/all.min.css' %}">

<link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

templates/partials/_messages.html
{% if messages %}
<br>
{% for message in messages %}
<div class="alert {{ message.tags }}" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}

templates/partials/_nav.html
{% load bsfilters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <div class="container-fluid px-4">
            <a class="navbar-brand" href="{% url 'product:list' %}">E-commerce</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Account
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'order:list' %}">My Orders</a></li>
                            <li><a class="dropdown-item" href="{% url 'profile:create' %}">Profile Update</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'profile:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:create' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:create' %}">Create Account</a>
                    </li>
                    {% endif %}

                    {% if request.session.cart %}
                    <li class="nav-item">
                        <a class="nav-link nav-cart-link active" href="{% url 'product:cart' %}">
                            <span class="nav-cart-text me-1">
                                Cart
                            </span>
                            <span class="nav-cart-count me-1">
                                <strong>{{ request.session.cart|cart_total_qty }}x</strong>
                            </span>
                            <span class="nav-cart-icon me-2">
                                <i class="fas fa-shopping-cart"></i>
                            </span>
                        </a>
                    </li>
                    {% endif %}

                </ul>
                <form class="d-flex" role="search" method="GET" action="{% url 'product:search' %}">
                    <input name="term" value="{{ request.GET.term }}" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-secondary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </div>

templates/partials/_order.html
{% load static %}
{% load bsfilters %}

<div class="row">
    <div class="col">
        <h3>{{ order }}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Order number:</div>
            <div class="col-lg-4">{{ order.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total to pay:</div>
            <div class="col-lg-4">{{ order.total|format_price_usa  }}</div>

            <div class="col-lg-2 font-weight-bold">QTY. Items:</div>
            <div class="col-lg-4">{{ order.total_qty }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ order.get_status_display }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Products</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Image</th>
                    <th>Product</th>
                    <th>V.</th>
                    <th>QTY.</th>
                    <th>Total</th>
                </tr>

                {% for row in order.orderitem_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{ row.image }}">
                    </td>
                    <td>{{ row.product }}</td>
                    <td>{{ row.variation }}</td>
                    <td>{{ row.quantity }}</td>
                    <td>
                        {% if row.promotional_price %}
                        {{ row.promotional_price|format_price_usa  }}
                        {% else %}
                        {{ row.price|format_price_usa  }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

templates/partials/_pagination.html
{% if is_paginated %}

<nav class="mt-4">
    <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}

    </ul>
</nav>

{% endif %}