orders/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('payment/<int:pk>', views.PaymentDetailView.as_view(), name="payment"),
    path('placeorder/', views.PlaceOrderView.as_view(), name="placeorder"),
    path('list/', views.OrderListView.as_view(), name="list"),
    path('detail/<int:pk>', views.OrderDetailView.as_view(), name="detail"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('orders.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
'''Models for Orders and Order Items in an e-commerce application.'''
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    ''' Order model '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    total_qty = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Approved'),
            ('C', 'Created'),
            ('R', 'Rejected'),
            ('P', 'Pending'),
            ('S', 'Shipped'),
            ('D', 'Delivered'),
        )
    )
    
    def __str__(self):
        return f"Order N. {self.pk}"

class OrderItem(models.Model):
    ''' Order Item model '''
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    price_promo = models.FloatField(default=0)
    quantity = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)
    
    def __str__(self):
        return f"Item from {self.order}"
    class Meta:
        ''' Meta class for OrderItem '''
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'

orders/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from django.contrib import messages

from products.models import Variation
from .models import Order, OrderItem

from utils import utils

class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('profile:create')
        
        return super().dispatch(*args, **kwargs)
    
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        return qs
class PaymentDetailView(DispatchLoginRequiredMixin, DetailView):
    template_name = 'order/payment.html'
    model = Order
    pk_url_kwarg = 'pk'
    context_object_name = 'order'
    
    def post(self, request, *args, **kwargs):
        order = self.get_object()
        messages.success(
            request,
            'Payment successful! Thank you for shopping with us.'
        )
        return redirect('product:list')

    

class PlaceOrderView(View):
    template_name = 'order/payment.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'You need to log in.'
            )
            return redirect('profile:create')
        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Empty cart.'
            )
            return redirect('product:list')

        cart = self.request.session.get('cart')
        cart_variation_ids = [v for v in cart]
        bd_variations = list(
            Variation.objects.select_related('product')
            .filter(id__in=cart_variation_ids)
        )
        for variation in bd_variations:
            vid = str(variation.id)

            stock = variation.stock
            qtd_cart = cart[vid]['quantity']
            unit_price = cart[vid]['unit_price']
            promo_unit_price = cart[vid]['promotional_unit_price']

            error_msg_stock = ''

            if stock < qtd_cart:
                cart[vid]['quantity'] = stock
                cart[vid]['quantitative_pricing'] = stock * unit_price
                cart[vid]['promotional_quantitative_pricing'] = stock * \
                    promo_unit_price

                error_msg_stock = 'Insufficient stock for some products in your cart. '\
                    'We have reduced the quantity of these products. Please '\
                    'check which products were affected below.'

                if error_msg_stock:
                    messages.error(
                        self.request,
                        error_msg_stock
                    )

                    self.request.session.save()
                    return redirect('product:cart')

        cart_total_qty = utils.cart_total_qty(cart)
        cart_total_amount = utils.cart_totals(cart)

        order = Order(
            user=self.request.user,
            total=cart_total_amount,
            total_qty=cart_total_qty,
            status='C',
        )

        order.save()

        OrderItem.objects.bulk_create(
            [
                OrderItem(
                    order=order,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_pricing'],
                    price_promo=v['promotional_quantitative_pricing'],
                    quantity=v['quantity'],
                    image=v['image'],
                ) for v in cart.values()
            ]
        )

        del self.request.session['cart']

        return redirect(
            reverse(
                'order:payment',
                kwargs={
                    'pk': order.pk,
                }
            )
        )

class OrderDetailView(DispatchLoginRequiredMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'order/detail.html'
    pk_url_kwarg = 'pk'

class OrderListView(DispatchLoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'order/list.html'
    paginate_by = 10
    ordering = ['-id']
    

orders/templates/order/detail.html
{% extends 'base.html' %}

{% block title %}{{ order }} | {% endblock %}

{% load bsfilters %}
{% load static %}

{% block content %}

{% include 'partials/_order.html' %}

{% endblock %}

orders/templates/order/list.html
{% extends 'base.html' %}
{% load bsfilters %}

{% block title %}{{ user.first_name }}'s orders | {% endblock %}

{% block content %}

<div class="row">
    <div class="col">
        <h3 class="mb-4">{{ user.first_name }}'s Orders</h3>
        <p>Below are all your orders placed in the store.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Order</th>
                    <th scope="col">Total</th>
                    <th scope="col">QTY. of Items</th>
                    <th scope="col">Status</th>
                    <th scope="col">More details</th>
                </tr>


                {% for order in orders %}
                <tr>
                    <th scope="row">{{ order }}</td>
                    <td>{{ order.total|format_price_usa }}</td>
                    <td>{{ order.total_qty }}</td>
                    <td>{{ order.get_status_display }}</td>
                    <td>
                        <a href="{% url 'order:detail' order.id %}">
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}


            </table>
        </div>
    </div>
</div>

{% include 'partials/_pagination.html' %}

{% endblock %}

orders/templates/order/payment.html
{% extends 'base.html' %}

{% block title %}Payment | {% endblock %}

{% load bsfilters %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col">
        <h3>Choose Your Payment Method</h3>
        <p>For the developer: add your preferred payment method.</p>
    </div>
</div>

{% include 'partials/_order.html' %}

<div class="row mt-4">
    <div class="col">
        <form method="post" action="{% url 'order:payment' order.pk %}">
            {% csrf_token %}
            <button class="btn btn-secondary w-100 btn-lg" type="submit">Pay</button>
        </form>
    </div>
</div>


{% endblock %}