orders/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('payment/<int:pk>', views.PaymentDetailView.as_view(), name="payment"),
    path('placeorder/', views.PlaceOrderView.as_view(), name="placeorder"),
    path('list/', views.OrderListView.as_view(), name="list"),
    path('detail/<int:pk>', views.OrderDetailView.as_view(), name="detail"),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name="list"),
    path('<slug>', views.ProductDetailView.as_view(), name="detail"),
    path('addtocart/', views.AddToCartView.as_view(), name="addtocart"),
    path('removefromcart/', views.RemoveFromCartView.as_view(), name="removefromcart"),
    path('cart/', views.CartView.as_view(), name="cart"),
    path('checkout/', views.CheckoutView.as_view(), name="checkout"),
    path('search/', views.SearchListView.as_view(), name="search"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.CreateProfileView.as_view(), name="create"),
    path('update/', views.UpdateProfileView.as_view(), name="update"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('orders.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
'''  This module defines the models for products and its variations '''

import os
from django.db import models
from django.conf import settings
from PIL import Image
from utils import utils
from django.utils.text import slugify

class Product(models.Model):
    ''' Product model '''
    name = models.CharField(max_length=255)
    short_description = models.TextField(max_length=255)
    long_description = models.TextField()
    image = models.ImageField(
        upload_to='product_images/%Y/%m', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    marketing_price = models.FloatField(verbose_name="Price")
    promotional_marketing_price = models.FloatField(default=0, verbose_name="Promo Price")
    type = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variable'),
            ('S', 'Simple'),
        )
    )
    
    def get_formatted_price(self):
        ''' Return formatted price '''
        return utils.format_price_usa(self.marketing_price)
    
    get_formatted_price.short_description = 'Price'
    
    def get_formatted_promotional_price(self):
        ''' Return formatted promotional price '''
        return utils.format_price_usa(self.promotional_marketing_price)
    
    get_formatted_promotional_price.short_description = 'Promo Price'

    @staticmethod
    def resize_image(img, new_width=800):
        ''' Resize image to new width '''
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        print(img_full_path)
        
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size
        
        if original_width <= new_width:
            img_pil.close()
            return
        
        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize(
            (new_width, new_height), Image.Resampling.LANCZOS)
        
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )
        
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f"{slugify(self.name)}"
            self.slug = slug
        
        super().save(*args, **kwargs)

        max_image_size = 800

        if self.image:
            self.resize_image(self.image, max_image_size)

    def __str__(self):
        return f"{self.name}"
    
class Variation(models.Model):
    ''' Product variation model '''
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True, null=True)
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    stock = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return self.name or self.product.name
    

products/views.py
"""
Views for the products application.

This module contains all the views related to product display and shopping
cart functionality. It includes class-based views for the main product
catalog (list and detail pages) and views to handle user interactions with
the session-based shopping cart, such as adding or removing items.
"""
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from django.db.models import Q

from .import models
from profiles.models import UserProfile

class ProductListView(ListView):
    """Displays a paginated list of all products."""
    model = models.Product
    template_name = "product/product_list.html"
    context_object_name = "products"
    paginate_by = 8
    ordering = ['-id']
    
class SearchListView(ProductListView):
    def get_queryset(self, *args, **kwargs):
        term = self.request.GET.get('term') or self.request.session['term']
        qs = super().get_queryset(*args, **kwargs)
        
        if not term:
            return qs
        
        self.request.session['term'] = term
        
        qs = qs.filter(
            Q(name__icontains=term) |
            Q(short_description__icontains=term) |
            Q(long_description__icontains=term)
        )
        
        self.request.session.save()
        return qs
class ProductDetailView(DetailView):
    """Displays the details for a single product."""
    model = models.Product
    template_name = "product/product_detail.html"
    context_object_name = "product"
    slug_rul_kwarg = 'slug'


class AddToCartView(View):
    """
    Adds a product variation to the shopping cart stored in the 
    user's session.
    
    This view is triggered by a GET request containing a 'vid' 
    (variation ID) query parameter. It handles adding new items, 
    incrementing the quantity of existing items, and validating 
    against available stock.
    """
    def get(self, *arg, **kwargs):
        """
        Handles the GET request to add an item to the cart. Redirects the
        user back to their previous page with a success or error message.
        """
        # if self.request.session.get('cart'):
        #     del self.request.session['cart']
        #     self.request.session.save()
            
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('product:list')
            )
        variation_id = self.request.GET.get('vid')
        
        
        if not variation_id:
            messages.error(
                self.request,
                'Non-existent product.'
            )
            return redirect(http_referer)

        variation = get_object_or_404(models.Variation, id=variation_id)
        variation_stock = variation.stock
        product = variation.product
        
        product_id = product.id
        product_name = product.name
        variation_name = variation.name or ''
        unit_price = variation.price
        promotional_unit_price = variation.promotional_price
        quantity = 1
        slug = product.slug
        image = product.image
        
        if variation.stock < 1:
            messages.error(
                self.request,
                'Out of stock'
            )
            return redirect(http_referer)
        
        if image:
            image = image.name
        else:
            image = ''
        
        if not self.request.session.get('cart'):
            self.request.session['cart'] = {}
            self.request.session.save()
            
        cart = self.request.session['cart']
        
        if variation_id in cart:
            cart_quantity = cart[variation_id]['quantity']
            cart_quantity += 1
                        
            if variation_stock < cart_quantity:
                messages.warning(
                    self.request,
                    f'Insufficient quantity for {cart_quantity}x on the '
                    f'"{product_name}" product. We\'ve added {variation_stock} '
                    f'to your shopping cart.'
                )
                cart_quantity = variation_stock
                
            cart[variation_id]['quantity'] = cart_quantity
            cart[variation_id]['quantitative_pricing'] = unit_price * \
                cart_quantity
            cart[variation_id]['promotional_quantitative_pricing'] = (
                promotional_unit_price * cart_quantity
            )

        else:
            cart[variation_id] = {
                'product_id': product_id,
                'product_name': product_name,
                'variation_name': variation_name,
                'variation_id': variation_id,
                'unit_price': unit_price,
                'promotional_unit_price': promotional_unit_price,
                'quantitative_pricing': unit_price,
                'promotional_quantitative_pricing': promotional_unit_price,
                'quantity': 1,
                'slug': slug,
                'image': image,
            }
            
        self.request.session.save()
        
        messages.success(
            self.request,
            f'Product "{product_name} {variation_name}" added to your '
            f'shopping cart {cart[variation_id]["quantity"]}x.'
        )
        
        return redirect(http_referer)

class RemoveFromCartView(View):
    '''Remove from cart operation'''
    def get(self, *args, **kwargs):
        '''Method to handle the items in the user session'''
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('product:list')
        )
        variation_id = self.request.GET.get('vid')
        
        if not variation_id:
            return redirect(http_referer)
        
        if not self.request.session.get('cart'):
            return redirect(http_referer)
        
        if variation_id not in self.request.session['cart']:
            return redirect(http_referer)
        
        cart = self.request.session['cart'][variation_id]
        
        messages.success(
            self.request,
            f'Product "{cart["product_name"]} - {cart["variation_name"]}" '
            f'removed from your cart.'
        )
        
        del self.request.session['cart'][variation_id]
        self.request.session.save()
        return redirect(http_referer)
        
class CartView(View):
    def get(self, *args, **kwargs):
        context = {
            'cart': self.request.session.get('cart', {})
        }
        return render(self.request, 'product/cart.html', context)
class CheckoutView(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('profile:create')
        
        profile = UserProfile.objects.filter(user=self.request.user).exists()
        
        if not profile:
            messages.error(
                self.request,
                'User without a profile.'
            )
            return redirect('profile:create')
        
        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Empty cart.'
            )
            return redirect('product:list')
        
        if not self.request.user.is_authenticated:
            return redirect('profile:create')
                
        context = {
            'user': self.request.user,
            'cart': self.request.session['cart'],
        }

        return render(self.request, 'product/checkout.html', context)

products/templates/product/cart.html
{% extends 'base.html' %}
{% load bsfilters %}

{% block title %}Cart | {% endblock %}

{% block content %}

{% if cart %}

<main class="container mt-4 mb-4">
    <div class="row mt-3">
        <div class="col">
            <h3>Shopping Cart</h3>
            <p class="lead">The products, quantities, and prices you selected.</p>

            {% include 'partials/_cart.html' %}
        </div>
    </div>



    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total in cart</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="fw-bold">Total</td>
                        <td>{{ cart|cart_totals|format_price_usa }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">

            {% if request.user.is_authenticated %}
            <a class="btn btn-lg w-100 btn-secondary" href="{% url 'product:checkout' %}">
                Buy
            </a>
            {% else %}
            <a class="btn btn-lg w-100 btn-secondary" href="{% url 'profile:create' %}">
                Log In or Register to Buy
            </a>
            {% endif %}
        </div>
    </div>

{% else %}

<div class="row mt-3">
    <div class="col">
        <h3>Empty Cart</h3>
        <p class="lead">There are no products in your cart.</p>
    </div>
</div>

{% endif %}

</main>

{% endblock %}

products/templates/product/checkout.html
{% extends 'base.html' %}
{% load bsfilters %}

{% block title %}Order Summary | {% endblock %}

{% block content %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Order Summary</h2>

        <p class="lead">User Data</p>
        <p>If you need to edit, <a href="{% url 'profile:create' %}">click here</a></p>
        <dl class="row">
            <dt class="col-lg-2">First name:</dt>
            <dd class="col-lg-4">{{ user.first_name }}</dd>
            <dt class="col-lg-2">Last name:</dt>
            <dd class="col-lg-4">{{ user.last_name }}</dd>

            <dt class="col-lg-2">Age:</dt>
            <dd class="col-lg-4">{{ user.profile.age }}</dd>
            <dt class="col-lg-2">Date of birth:</dt>
            <dd class="col-lg-4">{{ user.profile.birthdate }}</dd>

            <dt class="col-lg-2">CPF (ID):</dt>
            <dd class="col-lg-4">{{ user.profile.cpf }}</dd>
            <dt class="col-lg-2">Email:</dt>
            <dd class="col-lg-4">{{ user.email }}</dd>
        </dl>

        <p class="lead"></p>
        <p>If you need to edit, <a href="{% url 'profile:create' %}">click here</a></p>
        <dl class="row">
            <dt class="col-lg-2">Address:</dt>
            <dd class="col-lg-4">{{ user.profile.address }}</dd>
            <dt class="col-lg-2">Number:</dt>
            <dd class="col-lg-4">{{ user.profile.number }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ user.profile.complement }}</dd>
            <dt class="col-lg-2">Neighborhood:</dt>
            <dd class="col-lg-4">{{ user.profile.neighborhood }}</dd>

            <dt class="col-lg-2">City:</dt>
            <dd class="col-lg-4">{{ user.profile.city }}</dd>
            <dt class="col-lg-2">State:</dt>
            <dd class="col-lg-4">{{ user.profile.state }}</dd>

            <dt class="col-lg-2">ZIP code:</dt>
            <dd class="col-lg-4">{{ user.profile.zip_code }}</dd>
        </dl>
    </div>
</div>



<div class="row mt-3">
    <div class="col">
        <h3>Shopping Cart Summary</h3>
        <p class="lead">The products, quantities, and prices you selected.</p>

        {% include 'partials/_cart.html' %}
    </div>

</div>
<div class="row mt-3">
    <div class="col">
        <p class="lead text-center"><span class="fw-bold">Cart Total:</span>
            {{ cart|cart_totals|format_price_usa }}</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn w-100 btn-secondary btn-lg" href="{% url 'order:placeorder' %}">
            Place Order and Pay
        </a>
    </div>
</div>

{% endblock %}

products/templates/product/product_detail.html
{% extends 'base.html' %}
{% load bsfilters %}

{% block title %}{{  product.name  }} | {% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">
                {% if product.image %}
                <img class="img-fluid" src="{{product.image.url}}">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">
            <h1 class="h2">{{product.name}}</h1>
            <p class="lead">{{product.short_description|linebreaks}}</p>
            <p class="lead">
                {% if product.promotional_marketing_price %}
                <span id="variation-preco-promocional" class="lead product-price">
                    {{product.promotional_marketing_price|format_price_usa}}
                </span>
                <span id="variation-preco" class="lead product-old-price text-muted">
                    {{product.marketing_price|format_price_usa}}
                </span>
                {% else %}
                    <span id="variation-preco" class="lead product-price">
                        {{product.marketing_price|format_price_usa}}
                    </span>
                {% endif %}
            </p>

            <form action="{% url 'product:addtocart' %}" id="form-add-to-cart">
                <div class="form-group mb-3">
                    <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                        {% for variation in product.variation_set.all %}

                        {% if variation.promotional_price %}
                        <option data-preco="{{ variation.price|format_price_usa }}" 
                                data-preco-promocional="{{ variation.promotional_price|format_price_usa }}" 
                                value="{{ variation.id }}">
                            {% if variation.name %}
                            {{ variation.name }}
                            {% else %}
                            {{ variation }}
                            {% endif %}
                        </option>
                        {% else %}
                        <option data-preco="{{ variation.price|format_price_usa }}" value="{{ variation.id }}">   
                            {% if variation.name %}
                            {{ variatio.name }}
                            {% else %}
                            {{ variation }}
                            {% endif %}
                        </option>     
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="text-left">
                    <button type="submit" class="btn btn-secondary btn-lg w-100">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Add to Cart
                    </button>
                </div>
            </form>


        </div>
    </div>
</div>

<div class="row">
<div class="col-lg-12">
    <div class="mt-5 mb-5">
        <h2 class="text-center">{{product.name}}</h2>
            {{product.long_description|linebreaks}}
    </div>
</div>
</div>

{% endblock %}

products/templates/product/product_list.html
{% extends 'base.html' %}
{% load bsfilters %}

{% block title %}Products | {% endblock %}

{% block content %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
    {% for product in products %}

    <div class="col">
        <div class="card h-100">

            {% if product.image %}
            <a href="{% url 'product:detail' product.slug %}">
                <img class="card-img-top img-fluid"
                src="{{ product.image.url }}"
                alt="{{ product.name }}">
            </a>
            {% endif %}

            <div class="card-body d-flex flex-column">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.short_description }}</p>

                <div class="mt-auto">
                    {% if product.promotional_marketing_price %}
                        <div class="text-center">
                            <span class="product-price">
                                {{ product.promotional_marketing_price|format_price_usa }}
                            </span>
                            <span class="product-old-price text-muted">
                                {{ product.marketing_price|format_price_usa }}
                            </span>
                        </div>
                    {% else %}
                        <div class="text-center">
                            <span class="product-price">
                                {{ product.marketing_price|format_price_usa }}
                            </span>
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="card-footer bg-transparent border-top-light-custom text-center">
                <a href="{% url 'product:detail' product.slug %}"
                class="btn btn-secondary btn-sm w-100">
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    Buy
                </a>
            </div>

        </div>
    </div>

    {% endfor %}
</div>

<div class="col">
    {% include 'partials/_pagination.html' %}
</div>


{% endblock %}